### ISSUE TITLE
Error in building ZMQ

### ISSUE THREAD

**Issue by lorenzrichter** [JuliaInterop/ZMQ.jl#133]
When trying to run `IJulia` I get error messages from ZMQ. When subsequently trying to build ZMQ I get the following error message:

```julia> Pkg.build("ZMQ")
INFO: Building Homebrew
Already up-to-date.
INFO: Building ZMQ
=========================================[ ERROR: ZMQ ]=========================================

LoadError: KeyError: key "10.90" not found
while loading /Users/lorenz/.julia/v0.5/ZMQ/deps/build.jl, in expression starting on line 35

================================================================================================

========================================[ BUILD ERRORS ]========================================

WARNING: ZMQ had build errors.

 - packages with build errors remain installed in /Users/lorenz/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script

================================================================================================```

**Comment by ExpLog** [comment]
I'm having the same problem using Julia 0.5.0 and Fedora 25.

**Comment by wookay** [comment]
providing `versioninfo(true)` would be helpful.

**Comment by lorenzrichter** [comment]
Voila:

```Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
  WORD_SIZE: 64
  uname: Darwin 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 i386
Memory: 4.0 GB (17.953125 MB free)
Uptime: 1672.0 sec
Load Avg:  2.29736328125  1.6650390625  2.02587890625
Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz: 
       speed         user         nice          sys         idle          irq
#1  2400 MHz       3470 s          0 s       1257 s      12024 s          0 s
#2  2400 MHz       3454 s          0 s       1147 s      12137 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, penryn)
Environment:
  TERM = xterm-256color
  PATH = /Applications/Julia-0.5.app/Contents/Resources/julia/bin:/Users/lorenz/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin
  XPC_FLAGS = 0x0
  HOME = /Users/lorenz
  FONTCONFIG_PATH = /Applications/Julia-0.5.app/Contents/Resources/julia/etc/fonts

Package Directory: /Users/lorenz/.julia/v0.5
1 required packages:
 - IJulia                        1.4.1
9 additional packages:
 - BinDeps                       0.4.5
 - Compat                        0.14.0
 - Conda                         0.4.0
 - Homebrew                      0.4.2
 - JSON                          0.8.2
 - Nettle                        0.2.4
 - SHA                           0.3.0
 - URIParser                     0.1.7
 - ZMQ                           0.4.1```

**Comment by boarpig** [comment]
I have the same error when trying to run `Pkg.add("ZMQ")`

`=========================================================================[ ERROR: ZMQ ]=========================================================================

LoadError: Provider BinDeps.BuildProcess failed to satisfy dependency zmq
while loading /home/lauri/.julia/v0.5/ZMQ/deps/build.jl, in expression starting on line 35

================================================================================================================================================================

========================================================================[ BUILD ERRORS ]========================================================================

WARNING: ZMQ had build errors.

 - packages with build errors remain installed in /home/lauri/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script

================================================================================================================================================================`

BinDeps tried installing through apt-get and apt-get output shows that it was successful but for some reason BinDeps interprets that as a failure. I commented out aptget line from build.jl so that it would build from source, and the build succeeds but BinDeps still interprets that as  a failure.

Here's my versioninfo if it helps

`Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 4 (v7l)
  WORD_SIZE: 32
           Raspbian GNU/Linux 8.0 (jessie)
  uname: Linux 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l unknown
Memory: 0.8418769836425781 GB (300.9140625 MB free)
Uptime: 7670.0 sec
Load Avg:  0.8095703125  1.7626953125  1.16552734375
ARMv7 Processor rev 4 (v7l): 
       speed         user         nice          sys         idle          irq
#1   600 MHz      40181 s          0 s       4403 s     700868 s          0 s
#2   600 MHz      34910 s          0 s       3405 s     719010 s          0 s
#3   600 MHz      44505 s          0 s       3803 s     696536 s          0 s
#4   600 MHz      33909 s          0 s       4296 s     719533 s          0 s

  BLAS: libopenblas (NO_AFFINITY ARMV7)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.8.1 (ORCJIT, generic)
Environment:
  TERM = xterm-256color
  PATH = /home/lauri/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/lauri/.local/bin
  HOME = /home/lauri
  GOPATH = /home/lauri/go

Package Directory: /home/lauri/.julia/v0.5
1 required packages:
 - IJulia                        1.4.1
8 additional packages:
 - BinDeps                       0.4.7
 - Compat                        0.22.0
 - Conda                         0.5.3
 - JSON                          0.8.3
 - Nettle                        0.3.0
 - SHA                           0.3.2
 - URIParser                     0.1.8
 - ZMQ                           0.4.2              eacc2e19 (dirty)`

**Comment by boarpig** [comment]
I was using Julia `0.5.0` because the Arm binary for `0.5.1` was broken. I just installed latest nightly and everything seems to work just fine.

**Comment by lorenzrichter** [comment]
Hm, I'm not sure what exactly you mean. I tried it again and failed. Can you be more precise?

**Comment by tkelman** [comment]
>   CPU: ARMv7 Processor rev 4 (v7l)

That's almost certainly a separate unrelated issue.

**Comment by lorenzrichter** [comment]
Okay, thanks for pointing that out. Any idea what could be the issue in my case?

**Comment by tkelman** [comment]
@lorenzrichter I suspect what's probably happening for you is that you're still using OS X version 10.9, which is no longer supported by upstream Homebrew.

**Comment by lorenzrichter** [comment]
That's true. I will update and try again. Thank you!

**Comment by tkelman** [comment]
You could try commenting out the line `provides(Homebrew.HB, "staticfloat/juliadeps/zeromq32", zmq, os = :Darwin)` in `deps/build.jl` then see if `Pkg.build("ZMQ")` will build from source, you may be able to get things working that way.
