### ISSUE TITLE
ZMQ version problem

### ISSUE THREAD

**Issue by Student2Pro** [JuliaInterop/ZMQ.jl#201]
I install JuliaPro 1.3.1-2 today and when I add some pkg and it happened. 
![图片](https://user-images.githubusercontent.com/59324381/76683625-8dbaef80-6640-11ea-9700-588c0305e194.png)

I try these but they don't work
![图片](https://user-images.githubusercontent.com/59324381/76683617-7b40b600-6640-11ea-9bd8-718da8cdb87f.png)

I'm a julia beginner and it would be really helpful if anyone could tell me how to fix it.

**Comment by pablosanjose** [comment]
This problem is likely not due to ZMQ, but to some other package you installed that has an upper bound on compatible versions of ZMQ. You can try to find the offending package (have a look at `~/.julia/environments/v1.3/Manifest.toml` to see installed packages and their dependencies), remove it from your environment (doing `] rm packagename`) and add ZMQ again. Also, these types of questions should be rather posted in julialang.discourse.org, where you're likely to get a fast answer.
