### ISSUE TITLE
"using ZMQ" fails due to missing libzmq.5.dylib

### ISSUE THREAD

**Issue by fredcallaway** [JuliaInterop/ZMQ.jl#202]
I am trying to run a jupyter notebook with IJulia. It was working fine with 1.0, but on 1.3 I get the following when I try to use ZMQ (or IJulia)
```
 LoadError: InitError: could not load library "/Users/fred/.julia/artifacts/5fda443836f0ac9bd244dc4696216f20179c783e/lib/libzmq.5.dylib"
dlopen(/Users/fred/.julia/artifacts/5fda443836f0ac9bd244dc4696216f20179c783e/lib/libzmq.5.dylib, 1): image not found
```
I thought I could fix this by somehow forcing a reinstall of the library in assets, but I can't figure out how to do it... Apologies in advance if this is not due to a ZMQ-specific problem.

I can reproduce it with:
```
rm(Pkg.dir("ZMQ"), recursive=true, force=true)
Pkg.add("ZMQ")
using ZMQ
```

**Comment by stevengj** [comment]
The library is not in the `ZMQ` directory.  It's installed via the `ZeroMQ_jll` package.   What happens if you do `build ZMQ` at the package prompt?  or `add ZeroMQ_jll`?

In general, it sounds like you may have a corrupted `.julia` directory (e.g. by manually running `rm` on installed packages, which is dangerous), so you may just want to delete your whole `.julia` directory and re-install your packages.

**Comment by fredcallaway** [comment]
Thanks for the advice! For posterity, I think the problem may have been ultimately due to the `DYLD_FALLBACK_LIBRARY_PATH` environment variable because I was getting a similar error about not being able to open a dylib file with a completely fresh julia install until I removed that variable from my ENV.

**Comment by stevengj** [comment]
Can you file an issue at https://github.com/JuliaLang/Pkg.jl explaining what happened?   It seems like the binary artifacts system should be fixed so that it can't be affected by such environment variables.
